defaults:
  - override hydra/job_logging: disabled

serial_number: "1a86_USB_Serial"

ttf_server:
  port: 4050

catch:
  labels: ["bottle", "airplane"]
  area_min_limit: 0.6
  dev: "135122074193"
  move_time_interval: 1.1
  compensate:
    x: 0.0
    y: 0.0
    z: 0.00
